# Netlify配置文件
# 这个配置文件确保您的婚礼网站在Netlify上正确部署，并解决SPA路由问题

[build]
  # 指定构建输出目录
  publish = "dist"
  # 指定构建命令
  command = "npm run build"
  # 指定构建环境
  environment = { NODE_ENV = "production" }

# 缓存配置 - 加速构建过程
[build.environment]
  # 指定Node.js版本
  NODE_VERSION = "20"

# 重定向规则 - 解决SPA路由刷新404问题
[[redirects]]
  # 匹配所有路径
  from = "/*"
  # 重定向到index.html，让React Router处理路由
  to = "/index.html"
  # 使用200状态码而不是301/302重定向
  status = 200
  # 排除静态资源文件，让它们直接返回
  conditions = {
    Query = { path = "!.*\\.(js|css|png|jpg|jpeg|gif|svg|ico|woff2|woff|ttf|eot)$" }
  }

# 静态资源缓存策略
[[headers]]
  # 应用于所有静态资源文件
  for = "/*.{js,css,svg,png,jpg,jpeg,gif,ico,woff2,woff,ttf,eot}"
  [headers.values]
    # 设置30天的缓存时间
    Cache-Control = "public, max-age=2592000, immutable"

# 压缩配置
[functions]
  # 启用函数压缩
  node_bundler = "esbuild"

# 预览设置
[dev]
  # 本地开发端口
  port = 3000
  # 自动打开浏览器
  autoLaunch = true

# 分支部署配置
[context.production]
  # 生产环境构建命令
  command = "npm run build"

[context.deploy-preview]
  # 预览环境构建命令
  command = "npm run build"

[context.branch-deploy]
  # 分支部署构建命令
  command = "npm run build"